# Generated by Django 3.2.4 on 2021-06-14 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_student_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='students',
        ),
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.section'),
        ),
    ]
