# Generated by Django 3.2.4 on 2021-06-16 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210614_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Заметки'),
        ),
        migrations.AddField(
            model_name='student',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Заметки'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Заметки'),
        ),
    ]
