# Generated by Django 3.2.4 on 2021-06-18 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210616_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='watches_count',
            new_name='duties_count',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='puples_count',
            new_name='students_count',
        ),
        migrations.RemoveField(
            model_name='student',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='sections',
        ),
        migrations.AddField(
            model_name='teacher',
            name='section',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.section', verbose_name='Секция'),
        ),
    ]
