# Generated by Django 3.2.4 on 2021-06-16 20:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('puples_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество учеников')),
                ('watches_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество дежурств')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки')),
            ],
            options={
                'verbose_name': 'Секция',
                'verbose_name_plural': 'Секции',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second_name', models.CharField(max_length=64, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=64, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=64, verbose_name='Отчество')),
                ('qr_code', models.CharField(blank=True, max_length=512, unique=True, verbose_name='QR-код (путь)')),
                ('last_ate', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0), verbose_name='Последнее посещение столовой')),
                ('residence', models.CharField(blank=True, max_length=64, verbose_name='Искать в')),
                ('subjects', models.CharField(blank=True, max_length=256, verbose_name='Предмет/-ы')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки')),
                ('sections', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tickets.section', verbose_name='Секции')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second_name', models.CharField(max_length=64, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=64, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=64, verbose_name='Отчество')),
                ('qr_code', models.CharField(blank=True, max_length=512, verbose_name='QR-код (путь)')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('last_ate', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0), verbose_name='Последнее посещение столовой')),
                ('residence', models.CharField(blank=True, max_length=64, verbose_name='Искать в')),
                ('school', models.CharField(blank=True, max_length=128, verbose_name='Школа')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='День рождения')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки')),
                ('section', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tickets.section')),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
            },
        ),
    ]
