# Generated by Django 3.2.4 on 2021-08-28 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Казань', max_length=64, verbose_name='Город')),
                ('region', models.CharField(default='Татарстан', max_length=32, verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Имя')),
                ('surname', models.CharField(max_length=64, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=64, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='День рождения')),
                ('phone', models.CharField(max_length=16, verbose_name='Телефон')),
                ('tg', models.CharField(max_length=33, verbose_name='Телеграм')),
                ('inst', models.CharField(max_length=31, verbose_name='Инстаграм')),
                ('age', models.PositiveSmallIntegerField(default=0, verbose_name='Возраст')),
            ],
            options={
                'verbose_name': 'Родитель',
                'verbose_name_plural': 'Родители',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Секция')),
                ('students_count', models.PositiveSmallIntegerField(default=0, verbose_name='Число учеников')),
            ],
            options={
                'verbose_name': 'Секция',
                'verbose_name_plural': 'Секции',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Имя')),
                ('surname', models.CharField(max_length=64, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=64, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='День рождения')),
                ('phone', models.CharField(max_length=16, verbose_name='Телефон')),
                ('tg', models.CharField(max_length=33, verbose_name='Телеграм')),
                ('inst', models.CharField(max_length=31, verbose_name='Инстаграм')),
                ('age', models.PositiveSmallIntegerField(default=0, verbose_name='Возраст')),
                ('discipline', models.CharField(max_length=32, verbose_name='Предмет')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.city', verbose_name='Город')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='teacher_sections', to='core.section', verbose_name='Секция')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Имя')),
                ('surname', models.CharField(max_length=64, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=64, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='День рождения')),
                ('phone', models.CharField(max_length=16, verbose_name='Телефон')),
                ('tg', models.CharField(max_length=33, verbose_name='Телеграм')),
                ('inst', models.CharField(max_length=31, verbose_name='Инстаграм')),
                ('age', models.PositiveSmallIntegerField(default=0, verbose_name='Возраст')),
                ('qr', models.ImageField(blank=True, null=True, upload_to='students/qr/', verbose_name='QR')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.city', verbose_name='Город')),
                ('father', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='student_father', to='core.parent', verbose_name='Отец')),
                ('mother', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='student_mother', to='core.parent', verbose_name='Мать')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.section', verbose_name='Секция')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Квантовец',
                'verbose_name_plural': 'Квантовцы',
            },
        ),
        migrations.AddField(
            model_name='section',
            name='teachers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='section_teachers', to='core.teacher', verbose_name='Преподаватели'),
        ),
        migrations.AddField(
            model_name='parent',
            name='children',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.student', verbose_name='Дети'),
        ),
        migrations.AddField(
            model_name='parent',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.city', verbose_name='Город'),
        ),
    ]
