# Generated by Django 3.2.4 on 2021-08-29 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('core', '0001_initial'), ('core', '0002_auto_20210828_0411'), ('core', '0003_auto_20210828_0414'), ('core', '0004_auto_20210828_0414'), ('core', '0005_auto_20210828_0428'), ('core', '0006_auto_20210828_0430'), ('core', '0007_auto_20210828_0435'), ('core', '0008_auto_20210829_0008'), ('core', '0009_teacher_is_main'), ('core', '0010_auto_20210829_0521'), ('core', '0011_alter_student_section'), ('core', '0012_alter_student_section')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Казань', max_length=32, verbose_name='Город')),
                ('region', models.CharField(default='Татарстан', max_length=64, verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Секция')),
                ('students_count', models.PositiveSmallIntegerField(default=0, verbose_name='Число учеников')),
            ],
            options={
                'verbose_name': 'Секция',
                'verbose_name_plural': 'Секции',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Имя')),
                ('surname', models.CharField(max_length=64, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=64, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='День рождения')),
                ('phone', models.CharField(blank=True, max_length=16, verbose_name='Телефон')),
                ('tg', models.CharField(blank=True, max_length=33, verbose_name='Телеграм')),
                ('inst', models.CharField(blank=True, max_length=31, verbose_name='Инстаграм')),
                ('age', models.PositiveSmallIntegerField(default=0, verbose_name='Возраст')),
                ('discipline', models.CharField(max_length=32, verbose_name='Предмет')),
                ('city', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Имя')),
                ('surname', models.CharField(max_length=64, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=64, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='День рождения')),
                ('phone', models.CharField(blank=True, max_length=16, verbose_name='Телефон')),
                ('tg', models.CharField(blank=True, max_length=33, verbose_name='Телеграм')),
                ('inst', models.CharField(blank=True, max_length=31, verbose_name='Инстаграм')),
                ('age', models.PositiveSmallIntegerField(default=0, verbose_name='Возраст')),
                ('qr', models.ImageField(blank=True, null=True, upload_to='students/qr/', verbose_name='QR')),
                ('city', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.city', verbose_name='Город')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.section', verbose_name='Секция')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.teacher', verbose_name='Преподаватель')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='e-mail')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
            ],
            options={
                'verbose_name': 'Квантовец',
                'verbose_name_plural': 'Квантовцы',
            },
        ),
        migrations.AddField(
            model_name='section',
            name='teachers',
            field=models.ManyToManyField(blank=True, null=True, related_name='section_teachers', to='core.Teacher', verbose_name='Преподаватели'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='section',
            field=models.ManyToManyField(blank=True, null=True, related_name='teacher_sections', to='core.Section', verbose_name='Секция'),
        ),
        migrations.AlterField(
            model_name='section',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='section_teachers', to='core.Teacher', verbose_name='Преподаватели'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='section',
            field=models.ManyToManyField(blank=True, related_name='teacher_sections', to='core.Section', verbose_name='Секция'),
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Имя')),
                ('surname', models.CharField(max_length=64, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=64, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='День рождения')),
                ('phone', models.CharField(blank=True, max_length=16, verbose_name='Телефон')),
                ('tg', models.CharField(blank=True, max_length=33, verbose_name='Телеграм')),
                ('inst', models.CharField(blank=True, max_length=31, verbose_name='Инстаграм')),
                ('age', models.PositiveSmallIntegerField(default=0, verbose_name='Возраст')),
                ('city', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.city', verbose_name='Город')),
                ('children', models.ManyToManyField(blank=True, to='core.Student', verbose_name='Дети')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='e-mail')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Родитель',
                'verbose_name_plural': 'Родители',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='parents',
            field=models.ManyToManyField(blank=True, to='core.Parent', verbose_name='Родители'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='e-mail'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарии'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Руководитель секции'),
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.section', verbose_name='Секция'),
        ),
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.section', verbose_name='Секция'),
        ),
    ]
