# Generated by Django 3.2.4 on 2021-08-31 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210831_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='qr',
            field=models.ImageField(blank=True, null=True, upload_to='teachers/qr/', verbose_name='QR'),
        ),
    ]
