# Generated by Django 3.2.4 on 2021-09-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_teacher_qr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='patronymic',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='Фото (файл)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='patronymic',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='Фото (файл)'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='patronymic',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='Фото (файл)'),
        ),
    ]
