# Generated by Django 3.2.4 on 2021-08-28 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210828_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='teachers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='section_teachers', to='core.teacher', verbose_name='Преподаватели'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teacher_sections', to='core.section', verbose_name='Секция'),
        ),
    ]
