# Generated by Django 3.2.4 on 2021-09-02 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210901_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='student',
            name='qr',
            field=models.ImageField(blank=True, null=True, upload_to='students/qr', verbose_name='QR'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='qr',
            field=models.ImageField(blank=True, null=True, upload_to='teachers/qr', verbose_name='QR'),
        ),
    ]
