# Generated by Django 3.2.4 on 2021-08-28 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210828_0414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='children',
        ),
        migrations.AddField(
            model_name='parent',
            name='children',
            field=models.ManyToManyField(blank=True, null=True, to='core.Student', verbose_name='Дети'),
        ),
        migrations.RemoveField(
            model_name='student',
            name='father',
        ),
        migrations.AddField(
            model_name='student',
            name='father',
            field=models.ManyToManyField(blank=True, null=True, related_name='student_father', to='core.Parent', verbose_name='Отец'),
        ),
        migrations.RemoveField(
            model_name='student',
            name='mother',
        ),
        migrations.AddField(
            model_name='student',
            name='mother',
            field=models.ManyToManyField(blank=True, null=True, related_name='student_mother', to='core.Parent', verbose_name='Мать'),
        ),
    ]
