# Generated by Django 3.2.4 on 2021-08-28 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210828_0428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='teachers',
        ),
        migrations.AddField(
            model_name='section',
            name='teachers',
            field=models.ManyToManyField(blank=True, null=True, related_name='section_teachers', to='core.Teacher', verbose_name='Преподаватели'),
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='section',
        ),
        migrations.AddField(
            model_name='teacher',
            name='section',
            field=models.ManyToManyField(blank=True, null=True, related_name='teacher_sections', to='core.Section', verbose_name='Секция'),
        ),
    ]
