# Generated by Django 3.2.4 on 2021-09-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210902_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='qr',
            field=models.ImageField(blank=True, null=True, upload_to='qr', verbose_name='QR'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='qr',
            field=models.ImageField(blank=True, null=True, upload_to='qr', verbose_name='QR'),
        ),
    ]
