# Generated by Django 3.2.7 on 2021-09-06 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210902_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='qr',
            field=models.ImageField(blank=True, null=True, upload_to='qr/', verbose_name='QR'),
        ),
    ]
