# Generated by Django 3.2.4 on 2021-08-29 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210828_0435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='father',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mother',
        ),
        migrations.AddField(
            model_name='parent',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='e-mail'),
        ),
        migrations.AddField(
            model_name='parent',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарии'),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='e-mail'),
        ),
        migrations.AddField(
            model_name='student',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарии'),
        ),
        migrations.AddField(
            model_name='student',
            name='parents',
            field=models.ManyToManyField(blank=True, to='core.Parent', verbose_name='Родители'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='e-mail'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарии'),
        ),
    ]
