# Generated by Django 3.2.7 on 2021-09-06 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_student_qr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo/', verbose_name='Фото (файл)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo/', verbose_name='Фото (файл)'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo/', verbose_name='Фото (файл)'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='qr',
            field=models.ImageField(blank=True, null=True, upload_to='qr/', verbose_name='QR'),
        ),
    ]
