# Generated by Django 3.2.4 on 2021-08-29 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210829_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Руководитель секции'),
        ),
    ]
