# Generated by Django 3.2.4 on 2021-08-29 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_teacher_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='Казань', max_length=32, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='city',
            name='region',
            field=models.CharField(default='Татарстан', max_length=64, verbose_name='Регион'),
        ),
    ]
